# Generated by Django 5.2.17 on 2026-09-09 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RECEPCION', 'Recepción'), ('ALMACENAJE', 'Almacenaje'), ('PICKING', 'Picking'), ('DESPACHO', 'Despacho'), ('CUARENTENA', 'Cuarentena')], max_length=15)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='almacen.bodega')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['bodega', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pasillo', models.CharField(max_length=10)),
                ('rack', models.CharField(max_length=10)),
                ('nivel', models.CharField(max_length=10)),
                ('posicion', models.CharField(max_length=10)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=60, unique=True)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capacidad_m3', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='almacen.zona')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['zona', 'pasillo', 'rack', 'nivel', 'posicion'],
            },
        ),
        migrations.AddConstraint(
            model_name='zona',
            constraint=models.UniqueConstraint(fields=('bodega', 'codigo'), name='unico_codigo_zona_por_bodega'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('zona', 'pasillo', 'rack', 'nivel', 'posicion'), name='unica_ubicacion_fisica'),
        ),
    ]
