# Generated by Django 5.2.17 on 2026-09-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
