# Generated by Django 5.2.17 on 2026-09-09 00:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha_esperada', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Recibida parcialmente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('observacion', models.TextField(blank=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recepcion', to='catalogo.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de recepción',
                'verbose_name_plural': 'Órdenes de recepción',
                'ordering': ['-fecha_esperada'],
            },
        ),
        migrations.CreateModel(
            name='LineaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_esperada', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_recepcion', to='catalogo.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='recepcion.ordenrecepcion')),
            ],
            options={
                'verbose_name': 'Línea de recepción',
                'verbose_name_plural': 'Líneas de recepción',
                'constraints': [models.UniqueConstraint(fields=('orden', 'producto'), name='unico_producto_por_orden_recepcion')],
            },
        ),
    ]
