# Generated by Django 5.2.17 on 2026-09-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERARIO', 'Operario')], default='OPERARIO', max_length=20),
        ),
    ]
